[-release]Tagging version 6.0.7

diff --git a/src/etc/script/sympa.in b/src/etc/script/sympa.in
--- a/src/etc/script/sympa.in
+++ b/src/etc/script/sympa.in
@@ -22,19 +22,6 @@ if [ -f --initdir--/functions ]; then
     use_functions=1
 fi
 
-# Sympa parameters
-
-# Sympa binaries directory
-sympadir="--sbindir--"
-# Sympa config files directory
-sympaconf="--CONFIG--"
-wwsympaconf="--WWSCONFIG--"
-
-sympapiddir="--piddir--"
-sympalockdir="--lockdir--"
-
-
-
 if [ -f /etc/sysconfig/network ]; then
     # Get config.
     . /etc/sysconfig/network
@@ -64,6 +51,13 @@ if [ -f /etc/slackware-version ] ; then
     OSTYPE='Slack'
 fi
 
+# Sympa parameters
+# Sympa binaries directory
+sympadir="--sbindir--"
+
+# Sympa config files directory
+sympaconf="--CONFIG--"
+wwsympaconf="--WWSCONFIG--"
 
 ##'echo -n' not supported with SH on Solaris
 if [ ${OSTYPE} = "SunOS" ]; then
@@ -88,8 +82,8 @@ sympa_status() {
 
     else
        # First try "/u1/home/sympa/*.pid" files
-       if [ -f ${sympapiddir}/$1.pid ] ; then
-             pid=`head -1 ${sympapiddir}/$1.pid | tr -s ' ' '|'`
+       if [ -f --piddir--/$1.pid ] ; then
+             pid=`head -1 --piddir--/$1.pid | tr -s ' ' '|'`
              if [ "$pid" != "" ] ; then
                  running=`ps -A | egrep "$pid"`
                  if [ "$running" != "" ]; then
@@ -158,54 +152,32 @@ sympa_stop() {
         return 1
     fi
  
-    if [ -f ${sympapiddir}/$1.pid ]; then
-	echo $echo_opt "Stopping module $1.pl: "
-	pids=`head -1 ${sympapiddir}/$1.pid`
-	runcount=0
-	if [ "$pids" != "" ]; then
-	    for pid in $pids; do
-		killcount=0
-		running=`ps -A | grep "$pid ..* $1\\.pl"`
-		while [ "$running" != "" ]; do
-		    if [ $killcount -gt 10 ]; then
+	if [ -f --piddir--/$1.pid ]; then
+		echo $echo_opt "Stopping module $1.pl: "
+		pid=`head -1 --piddir--/$1.pid`
+		running=`ps -A | grep "$pid"`
+		if [ $1 = 'bulk' ]; then
+		    if [ ${use_functions} ]; then
+			kill -TERM $pid && success || failure
+		    else
+			kill -TERM $pid && echo "success" || echo "failure"
+		    fi		    
+		else 
+		    if [ "$running" != "" ]; then
 			if [ ${use_functions} ]; then
-			    failure
+			    kill -TERM $pid && success || failure
 			else
-			    echo 'failure'
-			fi
-			return 3
-		    fi
+			    kill -TERM $pid && echo "success" || echo "failure"
+			fi		    
 
-		    kill -TERM $pid >/dev/null 2>&1
-		    running=`ps -A | grep "$pid ..* $1\\.pl"`
-		    if [ "$running" = "" ]; then
-			runcount=`expr $runcount + 1`
-			break
+		    else
+			echo "died"
 		    fi
-		    sleep 2
-		    running=`ps -A | grep "$pid ..* $1\\.pl"`
-		    if [ "$running" = "" ]; then
-			runcount=`expr $runcount + 1`
-			break
-		    fi
-		    killcount=`expr $killcount + 1`
-		done
-	    done
-	fi
-	if [ $runcount -gt 0 ]; then
-	    if [ ${use_functions} ]; then
-		success
-	    else
-		echo 'success'
-	    fi
+		fi
+		echo
 	else
-	    echo 'died'
+	        echo "Module $1.pl not running"
 	fi
-	echo
-    else
-	echo "Module $1.pl not running"
-    fi
-    return 0
 }
 
 
@@ -225,14 +197,14 @@ fi
 # See how we were called.
 case "$1" in
   start)
-	if [ ! -f ${sympalockdir}/sympa ]; then
+	if [ ! -f --lockdir--/sympa ]; then
 		echo "Starting Sympa subsystem: "
 		sympa_start sympa
 		sympa_start bulk
 		sympa_start archived
 		sympa_start bounced
 		sympa_start task_manager
-		touch ${sympalockdir}/sympa
+		touch --lockdir--/sympa
 		echo
 	else
 
@@ -247,20 +219,20 @@ case "$1" in
 	sympa_stop archived
 	sympa_stop bulk
 	sympa_stop sympa
-	#if [ -f ${sympapiddir}/sympa-distribute.pid ]; then
-	#	sympa_stop sympa-distribute
-	#fi
-	if [ -f ${sympapiddir}/sympa-creation.pid ]; then
+	if [ -f --piddir--/sympa-distribute.pid ]; then
+		sympa_stop sympa-distribute
+	fi
+	if [ -f --piddir--/sympa-creation.pid ]; then
 		sympa_stop sympa-creation
 	fi
 	sympa_stop task_manager
-	if [ -f ${sympalockdir}/sympa ]; then
-		rm -f ${sympalockdir}/sympa
+	if [ -f --lockdir--/sympa ]; then
+		rm -f --lockdir--/sympa
 	fi
 	;;
   status)
 	echo "Status of Sympa subsystem: "
-	if [ -f ${sympalockdir}/sympa ]; then
+	if [ -f --lockdir--/sympa ]; then
 		echo "Status file for subsystem found."
 	else
 		echo "Status file for subsystem NOT found."
@@ -273,7 +245,9 @@ case "$1" in
 	;;
   restart)
 	echo "Restarting Sympa subsystem: "
-	$0 stop && $0 start
+	$0 stop
+	sleep 3
+	$0 start
 	echo
 	;;
   *)
@@ -283,4 +257,7 @@ case "$1" in
 esac
 
 exit 0
+
+
+
 
