replacing _ with . in tags/branches names

diff --git a/src/etc/script/sympa b/src/etc/script/sympa
--- a/src/etc/script/sympa
+++ b/src/etc/script/sympa
@@ -14,26 +14,9 @@
 # chkconfig: 345 95 05
 # description: sympa is a powerfull mailing lists management system.
 
-# OSTYPE is not defined on Solaris
-if [ ! "${OSTYPE}" ]; then
-    OSTYPE=`uname -s`
-fi
-
-if [ -f /etc/SuSE-release ] ; then
-    OSTYPE='Suse'
-fi
-
-if [ -f /etc/debian_version ] ; then
-    OSTYPE='Debian'
-fi
-
-if [ -f /etc/slackware-version ] ; then
-    OSTYPE='Slack'
-fi
-
-if [ ${OSTYPE} != "Slack" -a ${OSTYPE} != "FreeBSD" -a ${OSTYPE} != "SunOS" -a ${OSTYPE} != "darwin7.0" -a ${OSTYPE} != "Debian" -a ${OSTYPE} != "Suse" ]; then
+if [ ${OSTYPE} != "FreeBSD" ]; then
     # Source function library.
-    . --INITDIR--/functions
+    . /etc/rc.d/init.d/functions
 
     # Get config.
     . /etc/sysconfig/network
@@ -47,13 +30,6 @@ sympadir="--SBINDIR--"
 sympaconf="--CONFIG--"
 wwsympaconf="--WWSCONFIG--"
 
-##'echo -n' not supported with SH on Solaris
-if [ ${OSTYPE} = "SunOS" ]; then
-  echo_opt=""
-else
-  echo_opt="-n"
-fi
-
 # End of parameters
 
 # Current state of the module
@@ -64,28 +40,7 @@ sympa_status() {
         return 1
     fi
  
-    if [ ${OSTYPE} != "Slack" -a ${OSTYPE} != "FreeBSD" -a ${OSTYPE} != "SunOS" -a ${OSTYPE} != "darwin7.0"  -a ${OSTYPE} != "Debian" -a ${OSTYPE} != "Suse" ]; then
-
-      status $1.pl
-
-    else
-       # First try "/u1/home/sympa/*.pid" files
-       if [ -f --PIDDIR--/$1.pid ] ; then
-             pid=`head -1 --PIDDIR--/$1.pid`
-             if [ "$pid" != "" ] ; then
-                 running=`ps -A | grep "$pid"`
-                 if [ "$running" != "" ]; then
-                     echo "$1 (pid $pid) is active..."
-                     return 0
-                 else
-                     echo "$1 died, pid file remains."
-                     return 1
-                 fi
-             fi
-        fi
-        echo "$1 is stopped."
-        return 3
-    fi
+    status $1.pl
 }
 
 # Start a module
@@ -101,7 +56,7 @@ sympa_module_start() {
 #		startparam=""
 #	fi
  
-	if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
+	if [ ${OSTYPE} == "IRIX" ]; then
 		$sympadir/$1.pl $startparam && echo "success" || echo "failure"
 	else
 		$sympadir/$1.pl $startparam && success || failure
@@ -116,29 +71,15 @@ sympa_start() {
         return 1
     fi
  
+	echo -n "Starting module $1.pl: "
 	sympa_status $1 > /dev/null
 	case "$?" in
 		3)
-			echo $echo_opt "Starting module $1.pl: "
 			sympa_module_start $1
-			if [ ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" ]; then
-				if [ $? -eq 0 ]; then
-        	                       	echo "$1.pl started: success"
-	                       	else
-                	               	echo "$1.pl not started: failure"
-                       		fi
-			fi
 			;;
-		1) 
-			echo $echo_opt "Starting $1, overwritting old pid file."
+		1)
+			echo "Starting $1, overwritting old pid file."
 			sympa_module_start $1
-			if [ ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" ]; then
-				if [ $? -eq 0 ]; then
-        	                       	echo "$1.pl started: success"
-	                       	else
-                	               	echo "$1.pl not started: failure"
-                       		fi
-			fi
 			;;
 		0)
 			echo "$1 seems active. No action will be taken."
@@ -155,27 +96,21 @@ sympa_stop() {
     fi
  
 	if [ -f --PIDDIR--/$1.pid ]; then
-		echo $echo_opt "Stopping module $1.pl: "
+		echo -n "Stopping module $1.pl: "
 		pid=`head -1 --PIDDIR--/$1.pid`
-		running=`ps -A | grep "$pid"`
-		if [ "$running" != "" ]; then
-		if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
+		if [ ${OSTYPE} == "IRIX" ]; then
 			kill -TERM $pid && echo "success" || echo "failure"
-		    else
-			kill -TERM $pid && success || failure
-		    fi		    
 		else
-		    echo "died"
+			kill -TERM $pid && success || failure
 		fi
+		rm -f /var/run/$1.pl.pid
 		echo
-	else
-	        echo "Module $1.pl not running"
 	fi
 }
 
 
 # Check that networking is up.
-if [ ${OSTYPE} != "Slack" -a ${OSTYPE} != "FreeBSD" -a ${OSTYPE} != "SunOS" -a ${OSTYPE} != "darwin7.0" -a ${OSTYPE} != "Debian" -a ${OSTYPE} != "Suse" ]; then
+if [ ${OSTYPE} != "FreeBSD" ]; then
     if [ ${NETWORKING} = "no" ]
     then
 	    exit 0
@@ -195,7 +130,7 @@ case "$1" in
 		sympa_start sympa
 		sympa_start archived
 		sympa_start bounced
-		sympa_start task_manager
+#		sympa_start task_manager
 		touch --LOCKDIR--/sympa
 		echo
 	else
@@ -210,12 +145,6 @@ case "$1" in
 	sympa_stop bounced
 	sympa_stop archived
 	sympa_stop sympa
-	if [ -f --PIDDIR--/sympa-distribute.pid ]; then
-		sympa_stop sympa-distribute
-	fi
-	if [ -f --PIDDIR--/sympa-creation.pid ]; then
-		sympa_stop sympa-creation
-	fi
 	sympa_stop task_manager
 	if [ -f --LOCKDIR--/sympa ]; then
 		rm -f --LOCKDIR--/sympa
@@ -223,10 +152,11 @@ case "$1" in
 	;;
   status)
 	echo "Status of Sympa subsystem: "
+	echo -n "Status file for subsystem "
 	if [ -f --LOCKDIR--/sympa ]; then
-		echo "Status file for subsystem found."
+		echo "found."
 	else
-		echo "Status file for subsystem NOT found."
+		echo "NOT found."
 	fi
 	sympa_status sympa
 	sympa_status archived
@@ -236,7 +166,6 @@ case "$1" in
   restart)
 	echo "Restarting Sympa subsystem: "
 	$0 stop
-	sleep 3
 	$0 start
 	echo
 	;;
