[-release]Tagging version 6.2a.33

diff --git a/src/etc/script/sympa.in b/src/etc/script/sympa.in
--- a/src/etc/script/sympa.in
+++ b/src/etc/script/sympa.in
@@ -28,7 +28,6 @@ fi
 sympadir="--sbindir--"
 # Sympa config files directory
 sympaconf="--CONFIG--"
-wwsympaconf="--WWSCONFIG--"
 
 sympapiddir="--piddir--"
 sympalockdir="--lockdir--"
@@ -104,6 +103,24 @@ sympa_status() {
         echo "$1 is stopped."
         return 3
     fi
+}
+
+# Health check
+sympa_check() {
+	echo $echo_opt "Checking environment: "
+	if [ ${use_functions} ]; then
+		$sympadir/sympa.pl --health_check && success || failure
+		return $?
+	else
+		if $sympadir/sympa.pl --health_check; then
+			echo "success"
+			return 0
+		else
+			echo "failure"
+			return 1
+		fi
+	fi
+        echo
 }
 
 # Start a module
@@ -220,14 +237,15 @@ fi
 # Check config files
 [ -d $sympadir ] || exit 0
 [ -f $sympaconf ] || exit 0
-[ -f $wwsympaconf ] || exit 0
 
 # See how we were called.
 case "$1" in
   start)
 	if [ ! -f ${sympalockdir}/sympa ]; then
 		echo "Starting Sympa subsystem: "
+		sympa_check || exit 1
 		sympa_start sympa
+		sympa_start spooler
 		sympa_start bulk
 		sympa_start archived
 		sympa_start bounced
@@ -243,6 +261,7 @@ case "$1" in
 	;;
   stop)
 	echo "Stopping Sympa subsystem: "
+	sympa_stop spooler
 	sympa_stop bounced
 	sympa_stop archived
 	sympa_stop bulk
@@ -265,6 +284,7 @@ case "$1" in
 	else
 		echo "Status file for subsystem NOT found."
 	fi
+	sympa_status spooler
 	sympa_status sympa
 	sympa_status bulk
 	sympa_status archived
